# Generated by Django 5.2.14 on 2026-05-28 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_procedimiento', models.CharField(choices=[('INTERNO', 'Interno (realizado en el centro)'), ('EXTERNO', 'Externo (realizado fuera del centro)')], default='INTERNO', max_length=10)),
                ('nombre_procedimiento', models.CharField(default='', max_length=200, verbose_name='Nombre del Procedimiento')),
                ('medico_que_aplico', models.CharField(blank=True, max_length=200, null=True)),
                ('sitio_procedimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='procedimientos_externos/')),
                ('descripcion', models.TextField(verbose_name='Protocolo Aplicado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Novedades')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.identificacion')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procedimiento Médico',
                'verbose_name_plural': 'Procedimientos Médicos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
