# Generated by Django 5.2.14 on 2026-06-01 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_procedimientomedico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_profesional', models.CharField(blank=True, max_length=100, verbose_name='Matrícula / Registro Profesional')),
                ('especialidad', models.CharField(blank=True, max_length=150, verbose_name='Especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Profesional',
                'verbose_name_plural': 'Perfiles Profesionales',
            },
        ),
    ]
