# Generated by Django 5.2.7 on 2025-10-21 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_aspectosfisicos_fk_adversidades_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudades',
            new_name='Ciudad',
        ),
        migrations.RenameModel(
            old_name='DatosSocioeconomicos',
            new_name='DatosSocioeconomico',
        ),
        migrations.RenameModel(
            old_name='Departamentos',
            new_name='Departamento',
        ),
        migrations.RenameModel(
            old_name='Paises',
            new_name='Pais',
        ),
        migrations.RenameModel(
            old_name='TipoDocumentos',
            new_name='TipoDocumento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fk_espiritualidades',
        ),
        migrations.DeleteModel(
            name='GradosEscolaridad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fk_habitos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fk_seguridades_sociales',
        ),
        migrations.DeleteModel(
            name='Espiritualidades',
        ),
        migrations.DeleteModel(
            name='Habitos',
        ),
        migrations.DeleteModel(
            name='SeguridadesSociales',
        ),
    ]
