# Generated by Django 3.2.25 on 2025-11-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_evoluciondiaria_enfermeria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracionmental',
            old_name='restar_3_en_3',
            new_name='restar_tres_en_tres',
        ),
        migrations.AddField(
            model_name='aspectosfisicossalud',
            name='estado_salud',
            field=models.CharField(choices=[('BUENA', 'Buena'), ('REGULAR', 'Regular'), ('MALA', 'Mala')], default='BUENA', max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedentestoxicos',
            name='frecuencia_consumo',
            field=models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal')], max_length=10),
        ),
    ]
