# Generated by Django 3.2.25 on 2026-05-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20260210_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentos',
            name='empleado_encargado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicamentos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
